### PR TITLE
sim_tournal_internal was not exported

### PR DESCRIPTION
**Pull request by keberwein**
`sim_tournal_internal()` was not exported, which broke `walkTourney()`. Added `@export` to roxygen documentation and re-documented NAMESPACE.

### CODE REVIEW

**Comment by zachmayer** [comment]
Thanks!

**Comment by keberwein** [comment]
NP, great package BTW. Saved me a ton of time, which is what it's all about:D

**Comment by zachmayer** [comment]
Glad to hear it!

**Comment by zachmayer** [comment]
@keberwein I just pushed the new data, but think there's a bug in the bracket simulation.

Would you be willing to help me track it down?  THANKS!

-Zach

**Comment by keberwein** [comment]
Not a problem. I'm seeing that `sim_tourney_internal()` got added to the namespace in my commit. That was unintentional and may have something to do with it. Testing now, get back to you in a few.

**Comment by keberwein** [comment]
@zachmayer disregard my comment above. That function was, in fact, exported intentionally.

I reinstalled the current version of the package and can confirm everything looks good with 2016 data. However, when I run `simTourney(year=2017)`, it get the following error. 

```
Error in if (all_rounds[1] == 0) { : 
  missing value where TRUE/FALSE needed
```

**EDIT: This error was a result of user-error. I used 2016 preds and set the function to 2017.**

**Comment by zachmayer** [comment]
@keberwein My error was also user error (this time crunch is hard!).  My seed benchmark was incorrect, I fixed it.

Please take a look at the latest commit, I think it's correct now.

**Comment by keberwein** [comment]
@zachmayer I just downloaded the 2017 sample file from the [Kaggle site](https://www.kaggle.com/c/march-machine-learning-mania-2017/data).

I can confirm, everything is working as expected.

Cheers to user error;)

**Comment by zachmayer** [comment]
👍 

Good luck with your submission!

**Pull request merged**
